title: Built Environment Edinburgh
tagline: to create a sustainable and resilient environment
description: >
  GitHub Page Powered by Jekyll

# Required for GitHub Pages

url: "https://ruibogithub.github.io"
baseurl: "/built-environment-edinburgh"
google_analytics: G-XXXXXXX
markdown: kramdown
theme: jekyll-theme-cayman
include:
  - _pages
sass:
  style: expanded
nav:
  - name: Home
    link: /
  - name: Talks
    link: /talks/
  - name: Resources
    link: /resources/
  - name: Facilitators
    link: /facilitators/
